### ISSUE TITLE
[BUG] Anticaptcha fails on CERTIFICADOS_UE

### ISSUE THREAD

**Issue by Josexv1** [Josexv1/cita-bot#1]
REF #https://github.com/Josexv1/cita-bot/commit/b3d10fe2284938cc06184ec8874a91b8efee3279

**Comment by Josexv1** [comment]
@joanbr11 can you try again with this code as your example.py

```
customer = CustomerProfile(
        anticaptcha_api_key="... your key here ...",
        auto_captcha=False,
        auto_office=True,
        chrome_driver_path="chromedriver",
        save_artifacts=True,
        province=Province.BARCELONA,
        operation_code=OperationType.CERTIFICADOS_UE,
        doc_type=DocType.PASSPORT,
        doc_value="748521438",
        country="COUNTRY",
        name="FULL NAME",
        year_of_birth="2022",
        phone="625989898",
        email="correo@correo.de",
        offices=[],
    )
```

I tested it and **works just fine** on my end, if it doesn't work, can you tell me the env you are running the project, OS, Python version, and Chromedriver version.

![imagen](https://user-images.githubusercontent.com/12077848/171039277-d014acbf-9be7-4dd0-aeed-91dba578eb71.png)

**Comment by Urbina09112022** [comment]
Amigo algun contacto para algunas dudas por favor

**Comment by Josexv1** [comment]
@Urbina09112022 puedes cear un nuevo Issue con tus dudas, bugs o features.
