### ISSUE TITLE
Como activar Webhook con IFTTT

### ISSUE THREAD

**Issue by Urbina09112022** [Josexv1/cita-bot#2]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Urbina09112022** [comment]
@Josexv1

**Comment by Josexv1** [comment]
* Necesitas entrar a la web https://webhook.site/
* Te aparecera un correo estilo e6efd453-99999999999999@email.webhook.site
El numero que aparece es tu TOKEN, deberas colocarlo en el customer
* Luego en IFTTT crear una receta para que cuando recibas un SMS con la palabra CITA PREVIA, envie el texto al correo con tu TOKEN.

Yo actualmente estoy usando [SMS Forwarder](https://play.google.com/store/apps/details?id=com.frzinapps.smsforward&hl=en&gl=US) para enviarmelo por correo con GMail.
